from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .shopping_historyViews import ShoppingHistoryListCreateView,ShoppingHistoryRetrieveUpdateDestroy,UserHistory
from .tourist_packageViews import TouristPackageListCreateView,TouristPackageRetrieveUpdateDestroy